# Generated by Django 4.2 on 2023-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Announcement Title')),
                ('file', models.FileField(upload_to='announcements', verbose_name='Upload File')),
                ('date', models.DateField()),
            ],
        ),
    ]
